### ISSUE TITLE
Global - Update "Card 1" Style

### ISSUE THREAD

**Issue by cody-c-cai** [strongloop/v4.loopback.io#11]
Card 1 _currently_ looks like this:

<img width="420" alt="screen shot 2018-05-17 at 10 18 10 am" src="https://user-images.githubusercontent.com/39348500/40193237-a49a0526-59bb-11e8-9a8a-0e49716fbee9.png">

Card 1 _should_ look like this:

![screen shot 2018-05-17 at 10 19 22 am](https://user-images.githubusercontent.com/39348500/40193312-cf1c7d92-59bb-11e8-9c93-f64d45ac28b9.png)

**Requested Changes**

- H5 should be in **medium text weight** (not regular)
- The blue line at the top of the card should be **Blue-D** (not Blue)
- Hover states need to be added (see hover states: https://ibm.box.com/s/edb162u2447w4ncb89n2gj0yz1wv56j3)

**Comment by shimks** [comment]
I've merged #21 which should fix this. PTAL

**Comment by cody-c-cai** [comment]
Looks good—thank you!
