### ISSUE TITLE
Home - Fix "Features" Layout

### ISSUE THREAD

**Issue by cody-c-cai** [strongloop/v4.loopback.io#15]
Features _currently_ looks like this:
<img width="851" alt="screen shot 2018-05-18 at 10 50 35 am" src="https://user-images.githubusercontent.com/39348500/40249951-8c1efb4a-5a89-11e8-9b10-d97bf90b8aa9.png">

Features _should_ look like this:
![screen shot 2018-05-18 at 10 50 52 am](https://user-images.githubusercontent.com/39348500/40249963-944d1c7a-5a89-11e8-9b41-4e6bc3cf20ee.png)

Things to change:
- The text column width is too big. Please lower the column width of the text to give more space between the text and their respective graphics. 
- The text should be centered to their respective graphic. Currently the text aligns to the top of the graphic, but the text should be centered—having equal distance between the top and bottom of the graphic.
- Double check spacing between the H3 header and the paragraph text. The distance between the two currently looks too small. The distance should be (24px | 1.5rem). Use Homepage SPEC for reference: https://ibm.box.com/s/j3gioglb9gtn2bn98cm2mqavy0lz1tfh
- Add "Learn More" links with arrow icons. The links should correlate to what was included in the site plan: https://ibm.box.com/s/cd30f7kbehzk41rhi0ys41y1uak02oje

**Comment by shimks** [comment]
I've merged #21 which should fix this partially (`Learn More` hasn't been fixed). Could you also take a look at the mobile version as well and see if it's up to the spec?

**Comment by cody-c-cai** [comment]
Besides the "Learn More" and Mobile version this looks good! I haven't addressed the mobile specs yet, but will do so and update this issue with a link when it is ready.

**Comment by dhmlau** [comment]
Due to current priorities, we won't have the bandwidth to work on this in a near future, therefore, I'm closing this issue now.
