### ISSUE TITLE
Global - Fix "Footer" Layout

### ISSUE THREAD

**Issue by cody-c-cai** [strongloop/v4.loopback.io#16]
Footer _currently_ looks like this:
<img width="1680" alt="screen shot 2018-05-18 at 11 11 23 am" src="https://user-images.githubusercontent.com/39348500/40250835-678fbc94-5a8c-11e8-827b-b31ae57eaac8.png">

Footer _should_ look like this:

![screen shot 2018-05-18 at 11 25 39 am](https://user-images.githubusercontent.com/39348500/40251467-3fab1848-5a8e-11e8-8c34-7af87895783a.png)

![screen shot 2018-05-18 at 11 11 50 am](https://user-images.githubusercontent.com/39348500/40250855-73aaa746-5a8c-11e8-86c0-1f4245c2f12f.png)

Things to change:
- Increase LB 4 Logo Icon Size. The icon width is _currently_ 40px wide and it _should_ be 54 px wide.
- LB 4 Logo should align to left of the column grid.
- The category labels (Product, Documentation, Support), should follow the "LABEL" text style (12 px size, SemiBold text weight)
- Footer is missing "Join Our Mailing List" section.

**Comment by dhmlau** [comment]
Due to current priorities, we won't have the bandwidth to work on this in a near future, therefore, I'm closing this issue now.
