### ISSUE TITLE
LB4 web site: Resources page

### ISSUE THREAD

**Issue by dhmlau** [strongloop/v4.loopback.io#26]
### Acceptance criteria
- [ ] create the Resources page according to the [blueprint](https://github.com/strongloop/v4.loopback.io/tree/master/blueprint)
https://github.com/strongloop/v4.loopback.io/blob/master/blueprint/lb4-spec-page-resources.png

**Comment by dhmlau** [comment]
@nabdelgadir , before we have a template, we're currently copying and pasting the header and footer.
- use the same `<head>`, possibly just change the title. 
- use the same `<nav>` or the section commented as `Navbar`.
- same for `<footer`>
Thanks!

**Comment by dhmlau** [comment]
For the Developer resources, I’m thinking to have: 
1. Explore the documentation (no change) 
2. View our GitHub issues (no change)
3. Visit our blog. (New. please review)
Description: Read up on the latest updates from our maintainers and more.
Link: https://strongloop.com/strongblog/tag_LoopBack.html  
4. Participate in Gitter chat room. (changes in description. please review)
Description: See the LoopBack Gitter room for real-time discussions with fellow users.

With that, the following will be removed: 
- Join our mailing list.  _We're not using mailing list anymore?_ 
- Learn from our Stackoverflow.  _We're trying to gear all the traffic to github._
- Contribute to Awesome LoopBack. _Duplicate of the github repo tile_

**Comment by DaveYVR** [comment]
4. I can also add a link to the gitter chat on the SL page.

- mailing list. Due to GDPR we no longer send out a StrongLoop newsletter through mailchimp. However, we will be having an online newsletter we will point people towards via our various channels. Note sure who else is using our download lists.

**Comment by dhmlau** [comment]
Closing as done. Thanks @nabdelgadir!
