### ISSUE TITLE
Make LB4 documentation L&F the same as web site

### ISSUE THREAD

**Issue by dhmlau** [strongloop/v4.loopback.io#28]
## Description / Steps to reproduce / Feature proposal
We should have:
- LB4 documentation L&F the same as the v4.loopback.io website
- LB4 location would be something like v4.loopback.io/doc

**Comment by virkt25** [comment]
Well, the `v4.loopback.io` will become `loopback.io` once the framework hits GA so I don't think we need to change the domain but definitely the look and feel (and the old docs can leverage the new look as they will continue to exist on the same site).

**Comment by dhmlau** [comment]
Tracking using the epic #64 .  Closing this as duplicate.
The LB4 documentation L&F is the same as v4.loopback.io.  Next step is to make everything into one site.
