### ISSUE TITLE
Global - Update "primary button" text style

### ISSUE THREAD

**Issue by cody-c-cai** [strongloop/v4.loopback.io#4]
The primary button **currently** looks like this: 
<img width="293" alt="screen shot 2018-05-16 at 12 42 25 pm" src="https://user-images.githubusercontent.com/39348500/40140123-e239863c-5906-11e8-9950-755e676f0f37.png">

- The text style is currently in a _regular text weight_

The primary button **should** look like this:
![screen shot 2018-05-16 at 12 43 48 pm](https://user-images.githubusercontent.com/39348500/40140139-f0a33ec0-5906-11e8-8347-cd9cc92eb02c.png)

- The text style should be in a _bold text weight_

_______________________________________________

Please reference "BUTTON" text style in the SPECS:
![screen shot 2018-05-16 at 12 45 32 pm](https://user-images.githubusercontent.com/39348500/40140179-0d52d04e-5907-11e8-9723-a9433317cd1a.png)

Please double check that the button aligns with all of the following SPECS:

Button Text Style - https://ibm.box.com/s/3883y2d5buou5espqzalz1crjs4za1x2
Button Component - https://ibm.box.com/s/orgn062ubjp48xwdqosh882vue9kqyaj
Button Hover State - https://ibm.box.com/s/edb162u2447w4ncb89n2gj0yz1wv56j3

___________________________________________________

Please change the primary button to the styling specified above for both the buttons in the **Hero Feature** at the top of the Homepage and the **Call to Action** at the bottom of the Homepage. As well as any future primary buttons that will be used throughout the designs.

**Comment by shimks** [comment]
I've merged #21 which should fix this. PTAL

**Comment by cody-c-cai** [comment]
This looks good thank you—closing issue!
