### ISSUE TITLE
lb4 model --config <filename.json> --yes appears to do nothing

### ISSUE THREAD

**Issue by jpegram2** [strongloop/v4.loopback.io#59]
## Description / Steps to reproduce / Feature proposal
I have a JSON schema file for a MYSQL table and I want to generate the model for it. Per another thread the usage is: lb4 model --config <filename.json> --yes however this appears to do nothing as it prompts for the same information as simply running lb4 model does.

Additional info:
This is the code used to generate the json file.
`  const usersSchemas = await dataSrc.discoverSchemas(
    'Users'
  );
  console.log(JSON.stringify(usersSchemas, null, 2));`

This is what the file looks like:
`{
  "Users": {
    "name": "Users",
    "options": {
      "idInjection": false,
      "mysql": {
        "schema": "api.macoutpost.site",
        "table": "Users"
      }
    },
    "properties": {
      "id": {`

It has something to do with the "Users": { block. Removing that and the command seems to work. It does build the file but it not correct. Here's a snippet of what get's built.

```
import {Entity, model, property} from '@loopback/repository';

@model()
export class Users extends Entity {
  @property({
    type: 'Number',
    required: true,
    length: 42,
    precision: 10,
    scale: 0,
    id: 1,
    mysql: [object Object],
  })
  id: Number;
```

## Current Behavior
Initiates the standard lb4 model prompts

## Expected Behavior
Generate a model.ts file

**Comment by dhmlau** [comment]
@jpegram2 , I've tried a similar scenario as you, described in here: https://github.com/strongloop/loopback-next/issues/1921.
I find using the output from `discoverSchemas` and feed it into `lb4 model --config` doesn't exactly give us what we need.  #1921 describes a better solution.  I'd encourage you to join the discussion over there.

**Comment by dhmlau** [comment]
I'd like to close this ticket in favor of https://github.com/strongloop/loopback-next/issues/1921. Thanks.
