### ISSUE TITLE
Spike: Explore keeping the existing doc generation mechanism in LB4 site

### ISSUE THREAD

**Issue by dhmlau** [strongloop/v4.loopback.io#65]
## Description / Steps to reproduce / Feature proposal
Related to https://github.com/strongloop/v4.loopback.io/issues/64

By now, we have somewhat explored using VuePress and Gatsby (by @jannyHou).  I think we should find out whether we can still keep the same infrastructure that we have in the existing docs site when porting it to v4.loopback.io.  

### Acceptance Criteria
- [ ] Try to port a portion of docs to v4.loopback.io
   - to see what breaks and how easy/difficult to fix it
- [ ] Share the findings and we can evaluate as a team whether it makes sense to reuse or better to recreate.

**Comment by jannyHou** [comment]
timebox to 5 days.

**Comment by dhmlau** [comment]
Closing it as done. We're moving the v4.loopback.io pages back to loopback.io
