### ISSUE TITLE
Make links to blog and twitter more visible in the web site

### ISSUE THREAD

**Issue by dhmlau** [strongloop/v4.loopback.io#66]
## Description / Steps to reproduce / Feature proposal

_Following up on the comment from @bajtos_

Proposed change is to make the 3 icons show up at the top right corner.  
<img width="1186" alt="Screen Shot 2019-04-14 at 8 24 20 AM" src="https://user-images.githubusercontent.com/25489897/56092843-72bf8880-5e8f-11e9-896e-6b22d4e15ba2.png">

The icons are coming from https://fontawesome.com/icons?d=gallery. 

Code change would be something like below.  It might be better way to group the three icons.

```
<li class="nav-item">
                    <a class="nav-link"><i class="fas fa-blog"></i></a>
                </li>
                <li class="nav-item" style="margin-left:0">
                    <a class="nav-link"><i class="fab fa-twitter"></i></a>
                </li>
                <li class="nav-item" style="margin-left:0">
                    <a class="nav-link"><i class="fab fa-linkedin"></i></i></a>
                </li>
```

In `<head>`, add:
```
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" crossorigin="anonymous">
```

## Expected Behavior

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment]
I haven't seen the icon for the blog post before, it would not occur to me to look for the blog there.

Personally, I'd prefer to have a link with a name on it. E.g. "Blog", but I can also imagine "News" and "Updates" on it. 

A mock-up:

<img width="1198" alt="Screen Shot 2019-04-15 at 14 03 26" src="https://user-images.githubusercontent.com/1140553/56131288-50a93180-5f87-11e9-93ed-928090448fda.png">

While we are changing the navbar, I feel there are too many items there. Can we merge "Resources" and "Docs" together?

FWIW, the Resources page is listing few latest blog posts and then points reader to https://strongloop.com/strongblog/tag_LoopBack.html, this page also contains links to various documentation sites.

Also the main v4 page contains a link to the blog at the bottom.

In that light, maybe there is no need to put `Blog` in the top navbar, and we can also remove `Docs` in favor of `Resources`?

Anyhow, I think the issue I reported applies to the current (v3) branded website only. I feel the new (v4) version makes the blog easy to find, no changes are needed.

**Comment by dhmlau** [comment]
Sorry that I misunderstood you meant both web sites should have a more visible link of the blog. 

> While we are changing the navbar, I feel there are too many items there. Can we merge "Resources" and "Docs" together?

With the above mockup, yes, seems like too many items. I'm thinking:
- `Getting Started`: can be removed.  There's a "Get started with LoopBack 4" in the main banner already
- `Resources` + `Docs`: +1 on combining
- `Contribute`: can be removed.  There are many ways that link to the "contributing" docs already.
- `GraphQL`, `Test Your APIs`: no change
- `Blog`: I actually don't mind to have a separate entry at the top to make it more visible for our users to see.

**Comment by dhmlau** [comment]
Closing it as done. (in loopback.io)
