### ISSUE TITLE
Global - Update "label" text style

### ISSUE THREAD

**Issue by cody-c-cai** [strongloop/v4.loopback.io#7]
The label text style **currently** looks like this:
<img width="229" alt="screen shot 2018-05-16 at 12 55 22 pm" src="https://user-images.githubusercontent.com/39348500/40140874-d628e9bc-5908-11e8-8dfc-46ea8035b267.png">

- The text style is currently in a _regular text weight and size 16 pt_

The label text style **should** look like this:
![screen shot 2018-05-16 at 12 55 35 pm](https://user-images.githubusercontent.com/39348500/40140886-dda11322-5908-11e8-80c5-ba0f58221bde.png)

- The text style should be in a _semibold text weight and size 12 pt_

______________________________

Please reference "LABEL" text style in the SPECS:
![screen shot 2018-05-16 at 12 55 58 pm](https://user-images.githubusercontent.com/39348500/40140896-e75b30be-5908-11e8-9f2e-49901799f239.png)

**Comment by shimks** [comment]
I've merged #21 which should fix this. PTAL

**Comment by cody-c-cai** [comment]
Thank you for the revision! The weight of the text is correct; however, now looking at the implementation, I believe there should be some "letter-spacing" for the "Developer Preview" LABEL Text Style. Please try adding a *letter-spacing of 0.5 px*.

**Comment by dhmlau** [comment]
Due to current priorities, we won't have the bandwidth to work on this in a near future, therefore, I'm closing this issue now.
