### ISSUE TITLE
Further use-case of this repository

### ISSUE THREAD

**Issue by shivaylamba** [strongloop/v4.loopback.io#70]
## Description / Steps to reproduce / Feature proposal
Is there a specific need of this repository since https://github.com/strongloop/loopback.io is the new and updated repository for Loopback.

**Comment by dhmlau** [comment]
@shivaylamba, thanks for pointing it out. There is actually no need for the repo. I was hoping to get the redirect working (i.e. if someone goes to v4.loopback.io, it will redirect them to loopback.io) before deprecating the repo.  Will look into this shortly. But let me put a note in the README.

**Comment by dhmlau** [comment]
@shivaylamba, I've updated the README in PR #71 about deprecating this repo, and set v4.loopback.io to redirect to loopback.io, so that we no longer rely on the content in this repo. 
Closing this issue as done. I'll be archiving this repo. Thanks.
