### ISSUE TITLE
Home - Hero Background graphic should stretch the width of browser

### ISSUE THREAD

**Issue by cody-c-cai** [strongloop/v4.loopback.io#8]
The Hero *currently* looks like this:
<img width="1680" alt="screen shot 2018-05-16 at 1 21 26 pm" src="https://user-images.githubusercontent.com/39348500/40141905-11e2a5b2-590c-11e8-9953-030e3cba2371.png">

- Currently the background graphic has a fixed width

The Hero *should* look like this:
![screen shot 2018-05-16 at 1 21 51 pm](https://user-images.githubusercontent.com/39348500/40141925-279c029a-590c-11e8-9c20-efcc60670e2a.png)

- The background graphic should bleed off the edges of the page and be the width of the browser

**Comment by shimks** [comment]
I've merged #21 which should fix this. PTAL

**Comment by dhmlau** [comment]
Due to current priorities, we won't have the bandwidth to work on this in a near future, therefore, I'm closing this issue now.
